### PR TITLE
adding skiff stats

### PR DESCRIPTION
**Pull request by mkusold**
A simple add of the skiff stats.
While I was in here though I noticed that this app already uses a analytics tracker called "Heap". I was wondering if it is desired to support them both? (Are we even still using Heap?)

### CODE REVIEW

**Review by jonborchardt — APPROVED** [review]

**Review by codeviking — APPROVED** [review]
This looks great. 

We should ping someone from ScholarPhi too, since I think they *might* be in a code freeze, so I'm not sure when we'll be able to release this.

**Comment by codeviking** [comment]
@mjlangan can you TAL? IIRC ScholarPhi is in a code-freeze, right?

**Comment by mjlangan** [comment]
Re: Heap -- Yes, this is necessary. S2 uses Heap for tracking user actions within our applications
Re: Freeze -- Yep, still frozen for one more week. Today is the last day of CHI so we'll unfreeze next Monday.

**Comment by mkusold** [comment]
> Re: Heap -- Yes, this is necessary. S2 uses Heap for tracking user actions within our applications
> Re: Freeze -- Yep, still frozen for one more week. Today is the last day of CHI so we'll unfreeze next Monday. That said, it's only a _deploy_ freeze (right @codeviking?) so I don't have an issue with code changes going into main.

@codeviking If I merge this PR, will an auto-deploy occur?

**Comment by codeviking** [comment]
@mkusold Nope.

The application details page in [Marina](https://marina.apps.allenai.org/a/s2-reader) shows the trigger in the bottom-right. Mousing over "Trigger: Branch" shows this:

Screen Shot 2021-05-17 at 1 17 02 PM

So the production site is currently based off of that branch, meaning merging this won't cause a deployment.  

Also, I noticed that there isn't a Skiff Stats "site" for this yet. There's steps [here](https://github.com/allenai/skiff/blob/main/docs-internal/Onboarding.md#step-3-set-up-usage-tracking) that detail how to do that. We'll want to create one for the `s2-reader.stats.allenai.org` URL before this goes live.

**Review by mjlangan — APPROVED** [review]

**Comment by mkusold** [comment]
> s2-reader.stats.allenai.org

All of your information was very useful and very appreciated. Thanks for showing me that trigger section and how to add a site to Goat Counter. The site should now be set up. I'll merge soon!

**Pull request merged**
